no change     /home1/04637/mdl2665/anaconda3/condabin/conda
no change     /home1/04637/mdl2665/anaconda3/bin/conda
no change     /home1/04637/mdl2665/anaconda3/bin/conda-env
no change     /home1/04637/mdl2665/anaconda3/bin/activate
no change     /home1/04637/mdl2665/anaconda3/bin/deactivate
no change     /home1/04637/mdl2665/anaconda3/etc/profile.d/conda.sh
no change     /home1/04637/mdl2665/anaconda3/etc/fish/conf.d/conda.fish
no change     /home1/04637/mdl2665/anaconda3/shell/condabin/Conda.psm1
no change     /home1/04637/mdl2665/anaconda3/shell/condabin/conda-hook.ps1
no change     /home1/04637/mdl2665/anaconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /home1/04637/mdl2665/anaconda3/etc/profile.d/conda.csh
no change     /home1/04637/mdl2665/.bashrc
No action taken.

     active environment : fenicsx-env
    active env location : /home1/04637/mdl2665/anaconda3/envs/fenicsx-env
            shell level : 2
       user config file : /home1/04637/mdl2665/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home1/04637/mdl2665/anaconda3  (writable)
      conda av data dir : /home1/04637/mdl2665/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home1/04637/mdl2665/anaconda3/pkgs
                          /home1/04637/mdl2665/.conda/pkgs
       envs directories : /home1/04637/mdl2665/anaconda3/envs
                          /home1/04637/mdl2665/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/4.18.0-305.12.1.el8_4.x86_64 rocky/8.4 glibc/2.28
                UID:GID : 839365:819760
             netrc file : None
           offline mode : False

TACC:  Starting up job 441840 
TACC:  Starting parallel tasks... 
nt 4000
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
TypeError: can only concatenate tuple (not "int") to tuple
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:15: RuntimeWarning: invalid value encountered in sqrt
  WGD=np.sqrt(depth/g)*g

WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:16: RuntimeWarning: invalid value encountered in sqrt
  SND=sigma*np.sqrt(depth/g)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:67: RuntimeWarning: invalid value encountered in true_divide
  c_out[:,2] = k*sigma/(np.sinh(2*k*depth)) *(dHdt + u*dHdx + v*dHdy) - temp*k*(dudx)

    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
WARNING:py.warnings:/home1/04637/mdl2665/FENICSx/CFx/wave.py:69: RuntimeWarning: divide by zero encountered in true_divide
  c_out[:,3] = sigma/(np.sinh(2*k*depth))*(dHdx*np.sin(theta)- dHdy*np.cos(theta)) + \

Traceback (most recent call last):
  File "/home1/04637/mdl2665/FENICSx/Shoaling_wetdry.py", line 191, in <module>
    dry_locs = dry_locs+ local_range[0]
TypeError: can only concatenate tuple (not "int") to tuple
TACC:  MPI job exited with code: 1 
TACC:  Shutdown complete. Exiting. 
